<?php
/**
 * Created by PhpStorm.
 * User: kongweitao
 * Date: 2019/1/22
 * Time: 14:03
 */
class ItemController extends BaseController
{
    private $itemModel;

    public function _initialize ()
    {
       parent::_initialize(); // TODO: Change the autogenerated stub

       $this->itemModel = new ItemModel();
    }

    // 首页方法，测试框架自定义DB查询
    public function index()
    {
        $items = $this->itemModel->selectAll();

        $this->assign('title', '全部条目');
        $this->assign('items', $items);
    }

    // 添加记录，测试框架DB记录创建（Create）
    public function add()
    {
        $data['item_name'] = $_POST['value'];
        $count = $this->itemModel->add($data);

        $this->assign('title', '添加成功');
        $this->assign('count', $count);
    }

    // 查看记录，测试框架DB记录读取（Read）
    public function view($id = null)
    {
        $item = $this->itemModel->select($id);

        $this->assign('title', '正在查看' . $item['item_name']);
        $this->assign('item', $item);
    }

    // 更新记录，测试框架DB记录更新（Update）
    public function update()
    {
        $data = array('id' => $_POST['id'], 'item_name' => $_POST['value']);
        $count = $this->itemModel->update($data['id'], $data);

        $this->assign('title', '修改成功');
        $this->assign('count', $count);
    }

    // 删除记录，测试框架DB记录删除（Delete）
    public function delete($id = null)
    {
        $count = $this->itemModel->delete($id);

        $this->assign('title', '删除成功');
        $this->assign('count', $count);
    }

}